server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.173.142/accommodation?serverTimezone=GMT%2B8
    username: root
    password: SCms2019.
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    date-format: yyyy-MM-dd
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  redis:
    host: 47.101.173.142
    timeout: PT30M
  session:
    store-type: redis
    timeout: PT30M
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    database: MYSQL
    show-sql: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: pageNum=page,pageSize=limit
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.yanyue.pojo
  configuration:
    aggressive-lazy-loading: false
    lazy-loading-enabled: true
    use-generated-keys: true
    map-underscore-to-camel-case: true
    cache-enabled: true

